# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Setup
title: BioSQL
logo: BioSQL-t.png
tagline: Database schema for annotated biological sequences
url: http://biosql.org
baseurl: /

author:
  name: BioSQL Contributors
  url: https://twitter.com/OBF_news

# Page settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


# Custom variables for Hyde theme
version: 1.0.1
github:
  repo: https://github.com/biosql/biosql

exclude:
  - Gemfile
  - node_modules
  - Dockerfile
  - serve-local.sh
